name: Regression Project CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: devops-cbd3375
          service_account_key: ${{ secrets.GCP_JSON }}
          export_default_credentials: true

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/devops-cbd3375/app1:latest .
          docker push gcr.io/devops-cbd3375/app1:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: gcr.io/devops-cbd3375/app1:latest
          service: app1
          region: us-west2
          platform: managed
          allow-unauthenticated: true
          env_vars: |
            FOO=bar
            ZIP=zap
