name: Regression Project CI/CD

on:
  push:
    branches:
      - main

jobs:
  
  deploy:
    #needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: devops-cbd3375
          service_account_key: ${{ secrets.GCP_JSON }}
          export_default_credentials: true

      - name: Configure docker for GCP
        run: gcloud auth configure-docker
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          #context: .
          push: true
          tags: gcr.io/devops-cbd3375/app1:latest
          build-args: |
            HTTP_PORT=5000

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: gcr.io/devops-cbd3375/app1:latest
          service: app1
          region: us-west2
          platform: managed
          allow-unauthenticated: true
          env_vars: |
            FOO=bar
            ZIP=zap
